import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './board/Header'
import Navigator from './board/Navigator'
import { Search02 } from './api/BoardList_api';
import BoardListStyle from '../styles/index.module.css';
import {React, useState, useEffect } from 'react';
import Link from 'next/link';

import { Card, Avatar, CardHeader, Typography } from '@mui/material';
import { red } from '@mui/material/colors';
import CardMedia from '@mui/material/CardMedia';
import CardContent from '@mui/material/CardContent';

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [currentTime, setCurrentTime] = useState(new Date());

  const koreanTime = currentTime.toLocaleTimeString('en-US', { timeZone: 'Asia/Seoul' });
  const [hours, minutes] = koreanTime.split(':').map(Number);
  const isServerDownTime = hours >= 3 && hours < 8 && minutes >= 0 && minutes <= 30;

  useEffect(() => {
    const fetchData = async () => {
      try {
        setCurrentTime(new Date());
        if(isServerDownTime){
          alert('서버Down 상태입니다.. 오전 9시 서버부팅 됩니다.');
        }
        setTimeout(() => {
          Search02().then((data) => {
            if(data.length > 0){
              setPosts(data);
            }
          });
        }, 100);
      } catch (error) {
        console.error('데이터를 가져오는 중 오류가 발생했습니다.', error);
      }
    };
    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>LJC Developer Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div style={mainContent}>
      <Navigator />

      <main className={styles.main}>
        <h1 className={styles.title}>
            {isServerDownTime ? '오전 03:00 ~ 08:30 서버Down...' : (
              <>
                Welcome to <a href="/">My Blog</a>
              </>
            )}
        </h1>
        <br></br><br></br>
        <div><h3>많이 찾는 게시글</h3></div>
        <div className={BoardListStyle.post_container}>
        {posts.map((post) => (
            <Card key={post.id} sx={{ maxWidth: 345 }} className={BoardListStyle.post_item}>
              <Link href={`/board/BoardWrite?id=${post.id}&content=${post.title.replace(/\s+/g, '-')}`}>
                <CardHeader
                  avatar={
                    <Avatar sx={{ bgcolor: red[500], width: '100%' }} aria-label="recipe">
                      {post.board_type}
                    </Avatar>
                  }
                  title={
                    <Typography variant="h6" sx={{ fontWeight: 'bold' }}>
                      {post.title}
                    </Typography>
                  }
                  subheader={post.ins_ymdhms}
                />
                <CardMedia
                  component="img"
                  height="194"
                  image={post.thumbnail_url}
                  alt="Post Thumbnail"
                />
                <CardContent>
                  <Typography variant="body2" color="text.secondary">
                    {post.privew_content}
                  </Typography>
                </CardContent>
              </Link>
            </Card>
          ))}
        </div>
      </main>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
};

const mainContent = {
  display: 'flex'
};
