import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from './board/Header'
import Navigator from './board/Navigator'
import { Search02 } from './api/BoardList_api';
import BoardListStyle from '../styles/index.module.css';
import {React, useState, useEffect } from 'react';
import Link from 'next/link';

import { Card, Avatar, CardHeader, Typography } from '@mui/material';
import { red } from '@mui/material/colors';
import CardMedia from '@mui/material/CardMedia';
import CardContent from '@mui/material/CardContent';

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(false);
  
  
  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        setTimeout(() => {
          Search02().then((data) => {
            if(data.length > 0){
              setPosts(data);
              setLoading(false);
            }
          });
        }, 100);
      } catch (error) {
        setLoading(false);
        console.error('데이터를 가져오는 중 오류가 발생했습니다.', error);
      }
    };
    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>LJC Developer Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta http-equiv="Content-Security-Policy" content="script-src 'self';"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div style={mainContent}>
      <Navigator />

      <main className={styles.main}>
        <br></br><br></br>
        <div><h3>많이 찾는 게시글</h3></div>
        {loading ? (
          <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
            <img src="/image/loading.gif" alt="Loading" />
          </div>
        ) : (
          <div className={BoardListStyle.post_container}>
          {posts.map((post) => (
              <Card key={post.id} sx={{ maxWidth: 345 }} className={BoardListStyle.post_item}>
                <Link href={`/board/BoardWrite?id=${post.id}&content=${post.title.replace(/\s+/g, '-')}`}>
                  <CardHeader
                    avatar={
                      <Avatar sx={{ bgcolor: red[500], width: '100%' }} aria-label="recipe">
                        {post.board_type}
                      </Avatar>
                    }
                    title={
                      <Typography variant="h6" sx={{ fontWeight: 'bold', fontFamily: "Pretendard Variable, Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, 'Helvetica Neue', 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', sans-serif" }}>
                        {post.title}
                      </Typography>
                    }
                    subheader={post.ins_ymdhms}
                  />
                  <CardMedia
                    component="img"
                    height="194"
                    image={post.thumbnail_url}
                    alt="Post Thumbnail"
                  />
                  <CardContent>
                    <Typography variant="body2" color="text.secondary">
                      {post.privew_content}
                    </Typography>
                  </CardContent>
                </Link>
              </Card>
            ))}
          </div>
        )}
      </main>
      </div>

      <footer className={styles.footer}>
          <p>
            <a href="https://github.com/LJC0831/my-blog"
                target="_blank"
                rel="noopener noreferrer">
              <span>저자 : LJC</span><br/>
              <span>이메일 : leejc831@naver.com</span><br/>
              <span>Copyright 2024. cocoder. All Rights Reserved.</span>
            </a>
          </p>
      </footer>
    </div>
  )
};

const mainContent = {
  display: 'flex'
};
