name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1  
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          project: dlwocns0831/my-blog
          stage: main
          yaml: |
            name: my-blog
            app: node@16
            options:
              env:
                - name: NODE_ENV
                  value: production
              ports: 3000
              build: yarn build
              install: npm install react-quill
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
